import { test, expect } from 'vitest';

import type { BundleEntry, BundleEntryGroup } from './entryGroup';
import { groupBundleEntries, hashBundleOptions } from './entryGroup';

test('groupEntries should split different option set', () => {
  const entries: BundleEntry[] = [
    {
      key: 'exports["."].node.require',
      module: "commonjs",
      mode: undefined,
      minify: false,
      sourcemap: true,
      platform: "node",
      entryPath: "./lib/index.cjs",
      sourceFile: ["/project/src/index.cjs", "/project/src/index.js"],
      outputFile: "/project/lib/index.cjs",
      customConditions: [],
    },
    {
      key: 'exports["."].node.import.development',
      module: "esmodule",
      mode: "development",
      minify: false,
      sourcemap: true,
      platform: "node",
      entryPath: "./lib/index.mjs",
      sourceFile: ["/project/src/index.mjs", "/project/src/index.js"],
      outputFile: "/project/lib/index.mjs",
      customConditions: [],
    },
    {
      key: 'exports["."].node.import.production',
      module: "esmodule",
      mode: "production",
      minify: true,
      sourcemap: true,
      platform: "node",
      entryPath: "./lib/index.min.mjs",
      sourceFile: ["/project/src/index.mjs", "/project/src/index.js"],
      outputFile: "/project/lib/index.min.mjs",
      customConditions: [],
    },
    {
      key: 'exports["."].browser.development',
      module: "commonjs",
      mode: "development",
      minify: false,
      sourcemap: true,
      platform: "browser",
      entryPath: "./lib/browser.js",
      sourceFile: ["/project/src/browser.cjs", "/project/src/browser.js"],
      outputFile: "/project/lib/browser.js",
      customConditions: [],
    },
    {
      key: 'exports["."].browser.production',
      module: "commonjs",
      mode: "production",
      minify: true,
      sourcemap: true,
      platform: "browser",
      entryPath: "./lib/browser.min.js",
      sourceFile: ["/project/src/browser.cjs", "/project/src/browser.js"],
      outputFile: "/project/lib/browser.min.js",
      customConditions: [],
    },
  ];

  expect(groupBundleEntries(entries)).toEqual<BundleEntryGroup>({
    [hashBundleOptions({ mode: undefined, module: 'commonjs', platform: 'node', sourcemap: true, minify: false, customConditions: [] })]: [
      {
        key: 'exports["."].node.require',
        module: "commonjs",
        mode: undefined,
        minify: false,
        sourcemap: true,
        platform: "node",
        entryPath: "./lib/index.cjs",
        sourceFile: ["/project/src/index.cjs", "/project/src/index.js"],
        outputFile: "/project/lib/index.cjs",
      customConditions: [],
      },
    ],
    [hashBundleOptions({ mode: 'development', module: 'esmodule', platform: 'node', sourcemap: true, minify: false, customConditions: [] })]: [
      {
        key: 'exports["."].node.import.development',
        module: "esmodule",
        mode: "development",
        minify: false,
        sourcemap: true,
        platform: "node",
        entryPath: "./lib/index.mjs",
        sourceFile: ["/project/src/index.mjs", "/project/src/index.js"],
        outputFile: "/project/lib/index.mjs",
      customConditions: [],
      },
    ],
    [hashBundleOptions({ mode: 'production', module: 'esmodule', platform: 'node', sourcemap: true, minify: true, customConditions: [] })]: [
      {
        key: 'exports["."].node.import.production',
        module: "esmodule",
        mode: "production",
        minify: true,
        sourcemap: true,
        platform: "node",
        entryPath: "./lib/index.min.mjs",
        sourceFile: ["/project/src/index.mjs", "/project/src/index.js"],
        outputFile: "/project/lib/index.min.mjs",
      customConditions: [],
      },
    ],
    [hashBundleOptions({ mode: 'development', module: 'commonjs', platform: 'browser', sourcemap: true, minify: false, customConditions: [] })]: [
      {
        key: 'exports["."].browser.development',
        module: "commonjs",
        mode: "development",
        minify: false,
        sourcemap: true,
        platform: "browser",
        entryPath: "./lib/browser.js",
        sourceFile: ["/project/src/browser.cjs", "/project/src/browser.js"],
        outputFile: "/project/lib/browser.js",
      customConditions: [],
      },
    ],
    [hashBundleOptions({ mode: 'production', module: 'commonjs', platform: 'browser', sourcemap: true, minify: true, customConditions: [] })]: [
      {
        key: 'exports["."].browser.production',
        module: "commonjs",
        mode: "production",
        minify: true,
        sourcemap: true,
        platform: "browser",
        entryPath: "./lib/browser.min.js",
        sourceFile: ["/project/src/browser.cjs", "/project/src/browser.js"],
        outputFile: "/project/lib/browser.min.js",
      customConditions: [],
      },
    ],
  })
});

test('groupEntries should merge same option set', () => {
  const entries: BundleEntry[] = [
    {
      key: 'exports["."].require',
      module: "commonjs",
      mode: undefined,
      minify: false,
      sourcemap: true,
      platform: "neutral",
      entryPath: "./lib/index.cjs",
      sourceFile: ["/project/src/index.cjs", "/project/src/index.js"],
      outputFile: "/project/lib/index.cjs",
      customConditions: [],
    },
    {
      key: 'exports["."].default.require',
      module: "commonjs",
      mode: undefined,
      minify: false,
      sourcemap: true,
      platform: "neutral",
      entryPath: "./lib/index.cjs",
      sourceFile: ["/project/src/index.cjs", "/project/src/index.js"],
      outputFile: "/project/lib/index.cjs",
      customConditions: [],
    },
    {
      key: 'exports["."].default.default.require',
      module: "commonjs",
      mode: undefined,
      minify: false,
      sourcemap: true,
      platform: "neutral",
      entryPath: "./lib/index.cjs",
      sourceFile: ["/project/src/index.cjs", "/project/src/index.js"],
      outputFile: "/project/lib/index.cjs",
      customConditions: [],
    },
  ];

  expect(groupBundleEntries(entries)).toEqual<BundleEntryGroup>({
    [hashBundleOptions({ mode: undefined, module: 'commonjs', platform: 'neutral', sourcemap: true, minify: false, customConditions: [] })]: [
      {
        key: 'exports["."].require',
        module: "commonjs",
        mode: undefined,
        minify: false,
        sourcemap: true,
        platform: "neutral",
        entryPath: "./lib/index.cjs",
        sourceFile: ["/project/src/index.cjs", "/project/src/index.js"],
        outputFile: "/project/lib/index.cjs",
      customConditions: [],
      },
      {
        key: 'exports["."].default.require',
        module: "commonjs",
        mode: undefined,
        minify: false,
        sourcemap: true,
        platform: "neutral",
        entryPath: "./lib/index.cjs",
        sourceFile: ["/project/src/index.cjs", "/project/src/index.js"],
        outputFile: "/project/lib/index.cjs",
      customConditions: [],
      },
      {
        key: 'exports["."].default.default.require',
        module: "commonjs",
        mode: undefined,
        minify: false,
        sourcemap: true,
        platform: "neutral",
        entryPath: "./lib/index.cjs",
        sourceFile: ["/project/src/index.cjs", "/project/src/index.js"],
        outputFile: "/project/lib/index.cjs",
      customConditions: [],
      },
    ],
  });
});